package model;
// Generated 05-jun-2018 19:49:38 by Hibernate Tools 4.3.1



/**
 * Access generated by hbm2java
 */
public class Access  implements java.io.Serializable {


     private AccessId id;
     private User user;

    public Access() {
    }

    public Access(AccessId id, User user) {
       this.id = id;
       this.user = user;
    }
   
    public AccessId getId() {
        return this.id;
    }
    
    public void setId(AccessId id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


