package model;
// Generated 05-jun-2018 19:49:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String email;
     private String name;
     private String lastname;
     private String enterprise;
     private String registerdate;
     private Set accesses = new HashSet(0);

    public User() {
    }

	
    public User(String email) {
        this.email = email;
    }
    public User(String email, String name, String lastname, String enterprise, String registerdate, Set accesses) {
       this.email = email;
       this.name = name;
       this.lastname = lastname;
       this.enterprise = enterprise;
       this.registerdate = registerdate;
       this.accesses = accesses;
    }

    public User(String email, String name, String lastname, String enterprise, String registerdate) {
        this.email = email;
        this.name = name;
        this.lastname = lastname;
        this.enterprise = enterprise;
        this.registerdate = registerdate;
    }
    
   
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEnterprise() {
        return this.enterprise;
    }
    
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise;
    }
    public String getRegisterdate() {
        return this.registerdate;
    }
    
    public void setRegisterdate(String registerdate) {
        this.registerdate = registerdate;
    }
    public Set getAccesses() {
        return this.accesses;
    }
    
    public void setAccesses(Set accesses) {
        this.accesses = accesses;
    }




}


